version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: 'StockManager'
    restart: always
    environment:
      - POSTGRES_USER=igor
      - POSTGRES_PASSWORD=1234
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
